categories:
  - id: sdk
    name: Psy-Q SDK
    paths:
      - slps_023.64/psyq
  - id: main
    name: Main Executable
    paths:
      - slps_023.64

expected_paths:
  asm: expected/asm
  src: expected/src

ignored_files:
  - slps_023.64/header

scratch:
  enabled: true
  platform: ps1
  compiler: gcc2.8.1-psx
  c_flags: "-Wall -Wa,--aspsx-version=2.79,--expand-div -g3 -O2 -G0"
  ctx_path: ctx/project.ctx.c
  build_ctx: true

output: ./objdiff.json